### ISSUE TITLE
docker-entrypoint.sh 这个文件在哪里呢？

### ISSUE THREAD

**Issue by zoushangqi** [AliyunContainerService/redis-cluster#5]
exec docker-entrypoint.sh redis-server /etc/redis/sentinel.conf --sentinel

docker-entrypoint.sh 这个文件在哪里呢？运行报错。

**Comment by denverdino** [comment]
那个文件在redis:3镜像中 /usr/local/bin/docker-entrypoint.sh 目录下

**Comment by ais-one** [comment]
请注意! Line endings of the files should be in LF, not CRLF, if you do at git pull on windows and the files are CRLF, change them to LF, otherwise to sentinel part will not run. 这个问题浪费了我不少时间...

**Comment by denverdino** [comment]
请参考 https://yq.aliyun.com/articles/68245
